### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by hugovk** [hugovk/python-logos#14]
# Python

* [x] https://indypy.org/
* [x] https://github.com/pyatl/branding/blob/master/pyatl-logo-optimized-web.png
* [x] https://pyjamas.live/ https://github.com/pyjamasconf/pyjamas.live
* [x] EuroPython 2015 https://www.europython-society.org/logos
* [x] https://github.com/talkpython/ https://twitter.com/talkpython https://www.facebook.com/talkpython
* [x] https://twitter.com/PythonCameroun/status/1227147473166196737
* [x] EuroPython 2021 https://www.europython-society.org/logos
* [x] https://twitter.com/PyConTW https://tw.pycon.org/2021/en-us
* [x] https://github.com/pyjamasconf/pyjamas.live/blob/master/img/organizers/pyjamas-big.png
* [x] https://www.pymug.com/
* [x] https://twitter.com/PyConLK
* [x] https://twitter.com/python_es/status/1537011502523240448
* [x] https://twitter.com/PythonMaps
* [x] https://python.ph https://twitter.com/pythonph
* [x] https://pycon.or.tz/ https://twitter.com/PyconTanzania
* [x] https://twitter.com/asso_python_fr
* [x] https://linktr.ee/pythoncoruna
* [x] https://ug.pycon.org/
* [x] https://t.me/pythonpescara
* [x] https://openastronomy.org/pyastro/logo/
* [ ] https://pythonpy.org/
* [ ] https://www.mediawiki.org/wiki/Manual:Pywikibot
* [ ] https://in.pycon.org/2023/
* [ ] https://github.com/pygreece
* [ ] https://www.meetup.com/es-ES/Python-Panama/
* [ ] https://fosstodon.org/@pyconindia/112218287991231914
* [ ] https://hablemospython.dev/otrascomunidades.html
* [ ] https://2025.pycon.gr/en/
* [ ] https://pythontogo.vercel.app/
* [ ] https://pycontg.pytogo.org/ new version 2025
* [ ] https://www.linkedin.com/company/python-north-west-uk/
* [ ] https://luma.com/mmw3o95g
* [ ] https://www.meetup.com/python-panama/events/313936699/
* [ ] https://cm.pycon.org/en/ 2026
* [ ] https://www.pyconsenegambia.org/en
 
# PyLadies

* [x] https://www.facebook.com/pages/category/Community/Seattle-PyLadies-636187023142380/ https://www.meetup.com/Seattle-PyLadies/ https://twitter.com/PyLadiesSEA
* [ ] https://www.meetup.com/en-AU/PyLadiesLondon/events/276091578/
* [ ] https://github.com/pyladies/pyladies-assets/pull/7/ locations/pyladies_aracati_br_logo.png
* [ ] https://github.com/pyladies/pyladies-assets/pull/7/ locations/pyladies_curitiba_br_logo.png
* [ ] https://github.com/pyladies/pyladies-assets/pull/7/ locations/pyladies_macae_br_logo.png
* [ ] https://github.com/pyladies/pyladies-assets/pull/7/ locations/pyladies_maceio_br_logo.png
* [ ] https://github.com/pyladies/pyladies-assets/pull/7/ locations/pyladies_rio_de_janeiro_br_logo.png
* [ ] https://twitter.com/pyladiesbkk
* [x] https://twitter.com/PyLadiesParis
* [ ] https://www.meetup.com/pyladies-lithuania/

 
Instructions in the [README](https://github.com/hugovk/python-logos/blob/main/README.md).

**Comment by keshri29** [comment]
anyone can please tell me what to do in this repo.

**Comment by hugovk** [comment]
The instructions are in the README:

https://github.com/hugovk/python-logos/blob/main/README.md
